version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/docroot:/docroot
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    build: php
    volumes:
      - ./nginx/docroot:/docroot
      - ./php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - ./mongodb/data/db:/data/db
      - ./mongodb/initdb:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express:latest
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "8080:8081"
