version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/docroot:/docroot
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    build: php
    volumes:
      - ./nginx/docroot:/docroot
      - ./php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hunter2
      MONGO_INITDB_DATABASE: solarsystemdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hunter2
